---

- block:
  - name: "Creat primary user group for '{{ item_user.key }}'"
    group:
      name: "{{ item_user.key }}"
      gid: "{{ item_user.value.gid | default(omit) }}"

  - name: "Create or update user '{{ item_user.key }}'"
    user:
      name: "{{ item_user.key }}"
      group: "{{ item_user.value.group | default(item_user.key) }}"
      # empty string removes user from all secondary groups
      groups: "{{ item_user.value.groups | join(',') if 'groups' in item_user.value else '' }}"
      append: "{{ item_user.value.append | default(omit) }}"
      shell: "{{ item_user.value.shell | default(users_default_shell) | default(omit) }}"
      password: "{{ item_user.value.password if item_user.value.password is defined else '!' }}"
      comment: "{{ item_user.value.comment | default(omit) }}"
      uid: "{{ item_user.value.uid | default(omit) }}"
      home: "{{ item_user.value.home | default(omit) }}"
      create_home: "{{ item_user.value.create_home | default(omit) }}"
      update_password: "{{ item_user.value.update_password | default(omit) }}"
      system: "{{ item_user.value.system | default(omit) }}"

  - name: "Update SSH public keys for user '{{ item_user.key }}'"
    authorized_key:
      user: "{{ item_user.key }}"
      key: "{{ (item_user.value.ssh_keys | join('\n')) if item_user.value.ssh_keys is defined else '' }}"
      follow: "{{ item_user.value.ssh_follow | default(omit) }}"
      state: present
      exclusive: yes
    ignore_errors: "{{ ansible_check_mode }}"
  when: item_user.value.state is not defined or
        item_user.value.state == 'present'

- block:
  - name: "Remove user '{{ item_user.key }}'"
    user:
      name: "{{ item_user.key }}"
      state: absent
      remove: "{{ item_user.value.remove | default(omit) }}"
      force: "{{ item_user.value.force | default(omit) }}"

  - name: "Delete primary user group for '{{ item_user.key }}'"
    group:
      name: "{{ item_user.key }}"
      state: absent
  when:
    - item_user.value.state is defined
    - item_user.value.state == 'absent'
